[pytest]
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s - %(levelname)s - %(message)s


markers=
    sanity
    regression


addopts= -vs
         --headed
         --browser=chromium
         --video=retain-on-failure
         --screenshot=only-on-failure
         --tracing=retain-on-failure
         --reruns 2
         --reruns-delay 1
         --html=myreport.html --self-contained-html --capture=tee-sys
         --alluredir=allure-reports/allure-results